import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import UserProvider from './providers/UserProvider'
import { createClient } from '@/lib/supabase/server'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // Create a server-side Supabase client and read the session/user.
  // This runs on the server for every request in the app router. We pass the
  // user down into the client-side UserProvider as `initialUser` so client
  // components can access it immediately.
  const supabase = await createClient()
  const {
    data: { session },
  } = await supabase.auth.getSession()

  const user = session?.user ?? null

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Apply saved/system theme ASAP to avoid flash */}
        <script
          dangerouslySetInnerHTML={{
            __html:
              "(() => { try { const t = localStorage.getItem('theme'); const prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches; const isDark = t ? t === 'dark' : prefersDark; const cls = document.documentElement.classList; if (isDark) cls.add('dark'); else cls.remove('dark'); } catch {} })();",
          }}
        />
        <UserProvider initialUser={user}>{children}</UserProvider>
      </body>
    </html>
  )
}
